

org.gradle.jvmargs=-Xmx4096M
android.useAndroidX=true
android.enableJetifier=true
# ? Fix Play Store 16 KB alignment issue
android.bundle.enableUncompressedNativeLibs=false
# ? Fix Android 15 16KB page size issue
android.bundle.enableUncompressedNativeLibs=false
android.experimental.testOptions.managedDevices.maxConcurrentDevices=1
android.defaults.buildfeatures.buildconfig=true